package com.cicosy.cmms.Entity;

public enum ServiceCentre {
    ZAKA,CHIVI,TRIANGLE,HARARE,MUROMBEDZI,KAROI,GURUVE,RUSAPE,NYANGA,BIRCHENOUGH,MT_DARWIN,MUTOKO,
    BEITBRIDGE,GWANDA,HWANGE,BULAWAYO,LUPANE,KWEKWE,GOKWE,CHIVHU
}
