package com.cicosy.cmms.Entity;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;
import java.time.LocalDateTime;
import java.util.List;

@Entity
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Station {
    //id
    @Id
    //autogenerated
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    private String name;

    private  double latitude,longitude;
    private ServiceCentre serviceCentre;
    private CatchmentArea catchmentArea;
    private Status status;

    @JsonDeserialize(using = LocalDateTimeDeserializer.class)
    private LocalDateTime closedTime,openTime;

    private double hoursLostToday;
    private double hoursLostPrev;

    //list of equipment

    private String equipments;




}
